### ISSUE TITLE
Is this paper accepted by NIPS Workshop or NIPS?

### ISSUE THREAD

**Issue by Chen-Qiu** [sciencefans/coco_loss#10]
In your arXiv version, it shows that this paper is accepted by NIPS Workshop 2017, while the current README of this project shows that this paper is accepted by NIPS.
NIPS and NIPS Workshop are quite different. The citation section in the current README is misleading and should be corrected?

**Comment by liuyuisanai** [comment]
Hi @Chen-Qiu ,
Sorry for the misleading. This paper was accepted by NIPS but was withdrawn by some mistakes made by us. So we re-submitted it to the workshop session. README has been revised. Many thanks for reminding us.

**Comment by Chen-Qiu** [comment]
Very thanks for your kind reply :)
